### ISSUE TITLE
Cannot lookup a carrier on localhost

### ISSUE THREAD

**Issue by DanielAbsi** [notsafety/phone-lookup#1]
Hi, 
Thanks you for building this tools.
I download your phone-lookup project and executed on my localhost / 80.
I was testing my VOIP phone number and It tell me that it's not working.
My phone number is +1 (332) 333-9958.
Thanks for fixing the bug or helping me.
Daniel

**Comment by notsafety** [comment]
Numverify's now blocked the vulnerability.
Sorry for that
